title: 2021 new year blog
author: jake063
email: Jake72sullivan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my Dev Blog, I should be updating it throughout the year with projects and assignments I complete.  
 
# social links
github_username: jake063 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
